### ISSUE TITLE
Compatibility with simfphys mod (request)

### ISSUE THREAD

**Issue by JokerR3310** [NanoAi/gm_apg#1]
This mod work just perfect with normal vehicles, but not with simfphys. 
Vehicles on simfphys base can be pushed by props freelly even if the prop are in "ghosted" state, otherwise 
if simfphys "base" entity added to bad entitys list all vehicles on that base will stay in "ghosted" state for ever, since it have 5 or 6 entities in one place.

http://steamcommunity.com/sharedfiles/filedetails/?id=771487490
is this possible ?

**Comment by NanoAi** [comment]
I'll check it out, probably just needs a custom check for simfphys just like I did with WAC.

**Comment by NanoAi** [comment]
Just wanted to give you a quick update since it has pretty much been a week since you've posted. I've not gotten around to this yet but I will soon. I'm just working on multiple other projects. ^^;

**Comment by JokerR3310** [comment]
Alright thanks.

**Comment by Fatalityh** [comment]
I'm also waiting for this, hopefully we'll have it soon :)

**Comment by Fatalityh** [comment]
Any updates?

**Comment by NanoAi** [comment]
Not yet I've been working on something else and as a result just haven't gotten around to looking at Simfphys. Old things are nice but new things are also nice.

**Comment by NanoAi** [comment]
I'm going to update it soon. 🔢

**Comment by NanoAi** [comment]
This should be fixed now, for some reason if you have ghosting enabled it makes them pink. Not sure how to fix that but I added an option to disable ghosting for all detected vehicles.

Edit: It currently doesn't work with the nocollide vehicles option but I'll look into that.

**Comment by JokerR3310** [comment]
Yea, thanks, it works. But now if you freeze prop inside any vehicle, that vehicle will fly away, the same thing with WAC helicopters, and also all vehicles on simfphys base can now go thru each other.

**Comment by NanoAi** [comment]
Vehicles being able to go through each-other is because they are made out of props. By default APG will make props no-collide with other props. I'll try to fix it but no promises.

The other bug is really strange but I'll test it out.

**Comment by NanoAi** [comment]
The reason the ghosting doesn't really work with these cars is because they are multiple props and I have to turn off ghosting for them because I have no way to tell if these props are actually one entity or not. I've tried GetChildren, GetParent, constraint.GetAllConstrainedEntities, nothing seemed to work consistently.

Prop vehicles (WAC, Simpfphys, etc) will go through each-other unless you set the new Ignore Vehicles toggle in the Ghosting area.
