### ISSUE TITLE
Collision Problem

### ISSUE THREAD

**Issue by bronemishka** [NanoAi/gm_apg#19]
Props and vehicles dont have collision with world entities like doors. This become a problem when players try to ride over bridge that presented as func_door. So if there any switch combination that would fix this?
![image](https://user-images.githubusercontent.com/18225557/58320468-5e729200-7e24-11e9-883b-f34b0ecc6d27.png)
![image](https://user-images.githubusercontent.com/18225557/58320501-6fbb9e80-7e24-11e9-98ee-3095476001da.png)

**Comment by bronemishka** [comment]
forgot to say that this issue were possible to fix in older version of this addon

**Comment by NanoAi** [comment]
Try whitelisting "func_door" and see if that works. But we'll test to see what's up and get back to you soon!

**Comment by bronemishka** [comment]
not worked, but i've added entity of vehicle in "Good Entities" and this issue seems to dissappear.
![image](https://user-images.githubusercontent.com/18225557/58368462-17ed6800-7ef6-11e9-8366-202e127f641f.png)

**Comment by AvarianKnight** [comment]
Can you go to your data folders and go to APG and paste your settings.txt here?

**Comment by bronemishka** [comment]
{"cfg":{"notifyLevel":{"desc":"Notification levels, refer to APG_notifyLevels","value":"admin"},"autoFreezeTime":{"desc":"Auto freeze timer (seconds)","value":120.0},"fadingDoorHook":{"desc":"Inject custom hooks into Fading Doors","value":true},"removeInvalidPhysics":{"desc":"Should we attempt to detect and remove invalid physics objects? (Entities with bad or no physics objects/Physics objects without models.)","value":false},"badEnts":{"desc":"Entities to ghost/control/secure (true if exact name, false if it is a pattern","value":{"gmod_":false,"wire_":false,"prop_physics":true,"keypad":false}},"vehIncludeWAC":{"desc":"Check for WAC vehicles.","value":true},"notifySounds":{"desc":"When notifications run do you want the sounds to play?","value":false},"bigLag":{"desc":"Maximum time (seconds) between 2 frames to trigger a cleanup","value":2.0},"blockToolRate":{"desc":"How fast can we use the toolgun before it gets blocked? (Clicks per second(s))","value":4.7059},"blockToolWorld":{"desc":"Prevent using the toolgun on the world.","value":false},"sleepyPhys":{"desc":"Activate FRZR9K (Sleepy Physics)","value":false},"physGunMaxRange":{"desc":"Max range a physics gun can go","value":700.0},"stackArea":{"desc":"Sphere radius for stack detection (gmod units)","value":15.0},"ghostColor":{"desc":"Color set on ghosted props","value":{"r":255.0,"b":255.0,"a":183.0,"g":255.0}},"stackMax":{"desc":"Max amount of entities stacked in a small area","value":15.0},"vehDamage":{"desc":"True to disable vehicles damages, false to enable.","value":false},"lagFunc":{"desc":"Function ran on lag detected, see APG_lagFuncs.","value":"ghost_unfrozen"},"blockToolSpam":{"desc":"Block players from spamming the toolgun.","value":true},"checkCanTool":{"desc":"Should tools be blocked on APG_CantPickup?","value":true},"unGhostingWhitelist":{"desc":"Entities that should be set back to their original (spawned) collision group when frozen/dropped.","value":{"gmod_sent_vehicle_":false}},"checkTooledEnts":{"desc":"Review entities near tool use.","value":true},"setTurboPhysics":{"desc":"Toggle sv_turbophysics.","value":true},"logLagDetected":{"desc":"Log when the server lags","value":true},"blockPhysgunReload":{"desc":"Block players from using physgun reload","value":false},"sleepyPhysHook":{"desc":"Hook FRZR9K into collision (Experimental)","value":false},"touchServerSettings":{"desc":"Should we override Server Settings? (Used for setting ConVars)","value":true},"vehAntiGhost":{"desc":"Toggle vehicle ghosting","value":false},"lagsCount":{"desc":"Number of consectuives laggy frames in order to run a cleanup.","value":8.0},"fadingDoorGhosting":{"desc":"Activate fading door ghosting","value":true},"allowPK":{"desc":"Allow prop killing","value":false},"lagFuncTime":{"desc":"Time (seconds) between 2 anti lag function (avoid spam)","value":8.0},"blockGravGunThrow":{"desc":"Toggle GravGun throwing.","value":true},"logStackCrashAttempt":{"desc":"Log when someone tries to lag/crash the server with stacker","value":true},"autoFreeze":{"desc":"Freeze every unfrozen prop each X seconds","value":false},"blockContraptionMove":{"desc":"Block players from moving contraptions","value":false},"fadingDoorStackMax":{"desc":"Maximum amount of fading doors that can be stacked in stackArea.","value":5.0},"lagTrigger":{"desc":"[Default: 75%] Differential threshold between current lag and average lag.","value":75.0},"invalidPhysicsWhitelist":{"desc":"Entities that shouldn't be removed if they don't have proper physics","value":[]},"blockToolDelay":{"desc":"How many seconds should we wait after we were stopped? (The aforementioned second(s))","value":1.0},"blockCreatorTool":{"desc":"Should we block the creator tool?","value":true},"notifyLagFunc":{"desc":"Do you want the notifyLevel to see the lagFunc that ran? (refer to APG_lagFuncs)","value":false},"fadingDoorStackNotify":{"desc":"Notify the players when their fading doors were removed","value":false},"vehNoCollide":{"desc":"True to disable collisions between vehicles and players","value":false},"alwaysFrozen":{"desc":"Set to true to auto freeze props on physgun drop (aka APG_FreezeOnDrop)","value":false},"developerDebug":{"desc":"Dev Logs (prints stuff)","value":false},"blockToolUnfreeze":{"desc":"Prevent the toolgun from unfreezing props.","value":false}},"modules":{"stack_detection":true,"lag_detection":true,"notification":true,"ghosting":true,"home":true,"misc":true,"canphysgun":true,"tools":true,"logs":true}}

**Comment by sarahsturgeon** [comment]
```js
{  
   "cfg":{  
      "notifyLevel":{  
         "desc":"Notification levels, refer to APG_notifyLevels",
         "value":"admin"
      },
      "autoFreezeTime":{  
         "desc":"Auto freeze timer (seconds)",
         "value":120.0
      },
      "fadingDoorHook":{  
         "desc":"Inject custom hooks into Fading Doors",
         "value":true
      },
      "removeInvalidPhysics":{  
         "desc":"Should we attempt to detect and remove invalid physics objects? (Entities with bad or no physics objects/Physics objects without models.)",
         "value":false
      },
      "badEnts":{  
         "desc":"Entities to ghost/control/secure (true if exact name, false if it is a pattern",
         "value":{  
            "gmod_":false,
            "wire_":false,
            "prop_physics":true,
            "keypad":false
         }
      },
      "vehIncludeWAC":{  
         "desc":"Check for WAC vehicles.",
         "value":true
      },
      "notifySounds":{  
         "desc":"When notifications run do you want the sounds to play?",
         "value":false
      },
      "bigLag":{  
         "desc":"Maximum time (seconds) between 2 frames to trigger a cleanup",
         "value":2.0
      },
      "blockToolRate":{  
         "desc":"How fast can we use the toolgun before it gets blocked? (Clicks per second(s))",
         "value":4.7059
      },
      "blockToolWorld":{  
         "desc":"Prevent using the toolgun on the world.",
         "value":false
      },
      "sleepyPhys":{  
         "desc":"Activate FRZR9K (Sleepy Physics)",
         "value":false
      },
      "physGunMaxRange":{  
         "desc":"Max range a physics gun can go",
         "value":700.0
      },
      "stackArea":{  
         "desc":"Sphere radius for stack detection (gmod units)",
         "value":15.0
      },
      "ghostColor":{  
         "desc":"Color set on ghosted props",
         "value":{  
            "r":255.0,
            "b":255.0,
            "a":183.0,
            "g":255.0
         }
      },
      "stackMax":{  
         "desc":"Max amount of entities stacked in a small area",
         "value":15.0
      },
      "vehDamage":{  
         "desc":"True to disable vehicles damages, false to enable.",
         "value":false
      },
      "lagFunc":{  
         "desc":"Function ran on lag detected, see APG_lagFuncs.",
         "value":"ghost_unfrozen"
      },
      "blockToolSpam":{  
         "desc":"Block players from spamming the toolgun.",
         "value":true
      },
      "checkCanTool":{  
         "desc":"Should tools be blocked on APG_CantPickup?",
         "value":true
      },
      "unGhostingWhitelist":{  
         "desc":"Entities that should be set back to their original (spawned) collision group when frozen/dropped.",
         "value":{  
            "gmod_sent_vehicle_":false
         }
      },
      "checkTooledEnts":{  
         "desc":"Review entities near tool use.",
         "value":true
      },
      "setTurboPhysics":{  
         "desc":"Toggle sv_turbophysics.",
         "value":true
      },
      "logLagDetected":{  
         "desc":"Log when the server lags",
         "value":true
      },
      "blockPhysgunReload":{  
         "desc":"Block players from using physgun reload",
         "value":false
      },
      "sleepyPhysHook":{  
         "desc":"Hook FRZR9K into collision (Experimental)",
         "value":false
      },
      "touchServerSettings":{  
         "desc":"Should we override Server Settings? (Used for setting ConVars)",
         "value":true
      },
      "vehAntiGhost":{  
         "desc":"Toggle vehicle ghosting",
         "value":false
      },
      "lagsCount":{  
         "desc":"Number of consectuives laggy frames in order to run a cleanup.",
         "value":8.0
      },
      "fadingDoorGhosting":{  
         "desc":"Activate fading door ghosting",
         "value":true
      },
      "allowPK":{  
         "desc":"Allow prop killing",
         "value":false
      },
      "lagFuncTime":{  
         "desc":"Time (seconds) between 2 anti lag function (avoid spam)",
         "value":8.0
      },
      "blockGravGunThrow":{  
         "desc":"Toggle GravGun throwing.",
         "value":true
      },
      "logStackCrashAttempt":{  
         "desc":"Log when someone tries to lag/crash the server with stacker",
         "value":true
      },
      "autoFreeze":{  
         "desc":"Freeze every unfrozen prop each X seconds",
         "value":false
      },
      "blockContraptionMove":{  
         "desc":"Block players from moving contraptions",
         "value":false
      },
      "fadingDoorStackMax":{  
         "desc":"Maximum amount of fading doors that can be stacked in stackArea.",
         "value":5.0
      },
      "lagTrigger":{  
         "desc":"[Default: 75%] Differential threshold between current lag and average lag.",
         "value":75.0
      },
      "invalidPhysicsWhitelist":{  
         "desc":"Entities that shouldn't be removed if they don't have proper physics",
         "value":[  

         ]
      },
      "blockToolDelay":{  
         "desc":"How many seconds should we wait after we were stopped? (The aforementioned second(s))",
         "value":1.0
      },
      "blockCreatorTool":{  
         "desc":"Should we block the creator tool?",
         "value":true
      },
      "notifyLagFunc":{  
         "desc":"Do you want the notifyLevel to see the lagFunc that ran? (refer to APG_lagFuncs)",
         "value":false
      },
      "fadingDoorStackNotify":{  
         "desc":"Notify the players when their fading doors were removed",
         "value":false
      },
      "vehNoCollide":{  
         "desc":"True to disable collisions between vehicles and players",
         "value":false
      },
      "alwaysFrozen":{  
         "desc":"Set to true to auto freeze props on physgun drop (aka APG_FreezeOnDrop)",
         "value":false
      },
      "developerDebug":{  
         "desc":"Dev Logs (prints stuff)",
         "value":false
      },
      "blockToolUnfreeze":{  
         "desc":"Prevent the toolgun from unfreezing props.",
         "value":false
      }
   },
   "modules":{  
      "stack_detection":true,
      "lag_detection":true,
      "notification":true,
      "ghosting":true,
      "home":true,
      "misc":true,
      "canphysgun":true,
      "tools":true,
      "logs":true
   }
}
```

Makes it easier to read when formatted

**Comment by AvarianKnight** [comment]
I'll look at this more when I have time off work.

**Comment by AvarianKnight** [comment]
@bronemishka Can I get the map that you're using?

**Comment by bronemishka** [comment]
It's gm_genesis

пт, 21 июн. 2019 г., 7:39 Avarian <notifications@github.com>:

**Comment by NanoAi** [comment]
No updates for quite a while, feel free to reopen if the issue is still around.
