### ISSUE TITLE
Can physgun issue

### ISSUE THREAD

**Issue by gmanc2** [NanoAi/gm_apg#20]
[ERROR] addons/gm_apg-master/lua/apg/modules/canphysgun.lua:33: attempt to index field 'plys' (a nil value)
  1. unknown - addons/gm_apg-master/lua/apg/modules/canphysgun.lua:33

**Comment by AvarianKnight** [comment]
Hey can you change line 33 from

`	if ent.APG_HeldBy and not ent.APG_HeldBy.plys[sid] then
`

to

`	if ent.APG_HeldBy and ent.APG_HeldBy.plys and not ent.APG_HeldBy.plys[sid] then
`

**Comment by AvarianKnight** [comment]
@gmanc2 Can you confirm that this fixed your issue?

**Comment by gmanc2** [comment]
This fixed it thank you
