### ISSUE TITLE
Conflicting with WAC

### ISSUE THREAD

**Issue by RadioactvePixels** [NanoAi/gm_apg#21]
I'm pretty much sure that APG v2 is preventing certain WAC vehicles from moving.

**Comment by AvarianKnight** [comment]
Need more information, what certain WAC vehicles.

**Comment by RadioactvePixels** [comment]
List of Planes/Helicopters that work- (Wac Aircraft): Cessna C172, Icon A5, Little Bird AH-6,Little Bird MH-6, -(WAC COMMUNITY):Aircreation 582SL,Bell OH-58D Kiowa,Curtiss JN-4 Jenny, Fw 190A-5  Wurger,Hughes 500D,Mitsubushi A6M2N Zero,Robinson R22,SuperMarine Spitfire V

**Comment by AvarianKnight** [comment]
Can you provide me with your config which would be in your garrysmod/data/apg folder.

**Comment by AvarianKnight** [comment]
Also is this a list of ones that do or don't work, i only need ones that dont.

**Comment by RadioactvePixels** [comment]
These are the ones that do work

**Comment by AvarianKnight** [comment]
I need to know the ones that aren't working so i can track down the issue.

**Comment by NanoAi** [comment]
No response in 15 days, assuming as resolved. Feel free to reopen if the issue persists.
