### ISSUE TITLE
Fading door

### ISSUE THREAD

**Issue by Mika32150** [NanoAi/gm_apg#23]
[ERROR] addons/apg/lua/apg/modules/stack_detection.lua:77: attempt to index field 'fadingDoorStackNotification' (a nil value)
1. fn - addons/apg/lua/apg/modules/stack_detection.lua:77
2. Run - addons/ulib/lua/ulib/shared/hook.lua:109
3. fadeActivate - addons/apg/lua/apg/modules/misc.lua:129
4. fadeToggleActive - addons/pichot/lua/weapons/gmod_tool/stools/fading_door.lua:289
5. func - addons/pichot/lua/weapons/gmod_tool/stools/fading_door.lua:298
6. FireImpulse - lua/includes/modules/numpad.lua:82
7. Deactivate - lua/includes/modules/numpad.lua:133
8. Toggle - gamemodes/sandbox/entities/entities/gmod_button.lua:132
9. unknown - gamemodes/sandbox/entities/entities/gmod_button.lua:109

**Comment by NanoAi** [comment]
Did you get it working?

**Comment by Mika32150** [comment]
Yes just uncheck "inject code" and revert it and it worked...
