### ISSUE TITLE
Can crash car

### ISSUE THREAD

**Issue by Mika32150** [NanoAi/gm_apg#24]
We can freeze a prop in a car for crash it.

Let's see : https://youtu.be/j9IBKMRQ0FE

**Comment by AvarianKnight** [comment]
Does this work with any other cars or just this single car? If it works with other cars can you give me the names of the cars that this is possible.

**Comment by Mika32150** [comment]
All cars... It seem to be logic

**Comment by Mika32150** [comment]
No news ?

**Comment by NanoAi** [comment]
Presumed resolved, feel free to reopen.
