### ISSUE TITLE
fading doors being broke

### ISSUE THREAD

**Issue by Aws0mee** [NanoAi/gm_apg#25]
When using this addon fading doors will randomly not be able to be faded and I can't seem to find a fix except for opening the !apg menu and pressing save. No clue why hitting save fixes the issue. If this could be fixed it would be very helpful because it's very annoying and I have to constantly fix it 1-2 times a day.

**Comment by Mika32150** [comment]
Same problem here !

**Comment by NanoAi** [comment]
Hello I no longer really play gmod as I'm focused on work, and trying to get my life in order now days.

...and after getting issue upon issue from APG I decided to remake it from the ground up. You can find the remake here...
https://gitlab.com/NanoAi/gm_pug

Please try it out and let me know if your issues are resolved.

**Comment by Aws0mee** [comment]
I'll try it out. Does it have all the same features of apg?

**Comment by NanoAi** [comment]
It has most of the features.

**Comment by Aws0mee** [comment]
Okay, thanks for your help and for continuing this kind of stuff. Pretty unfortunate 1,552 people bought apg which is literally broken now because the other dev just dipped :/

**Comment by NanoAi** [comment]
Yes, but there was nothing I could do about that. I couldn't update it on SF as I wasn't the uploader of the script.

So I decided that making it free and actually giving some sort of updates would be better then nothing.

**Comment by Mika32150** [comment]
Your work on this addon is great, i just downloaded pug. I wish it can help my server

**Comment by Mika32150** [comment]
[ERROR] addons/gm_pug_master/lua/pug/sv_pug.lua:156: Tried to use a NULL entity!
1. _SetPos - [C]:-1
2. SetPos - addons/gm_pug_master/lua/pug/sv_pug.lua:156
3. CreateEntity - addons/itemstore/lua/itemstore/items/base_entity.lua:10
4. DropItem - addons/itemstore/lua/itemstore/sv_player.lua:261
5. func - addons/itemstore/lua/itemstore/sv_player.lua:285
6. unknown - lua/includes/extensions/net.lua:32

**Comment by NanoAi** [comment]
Please post issues with PUG on the Gitlab.

Also that error is not from PUG, it just puts it on the top of the stack because of the detour.

**Comment by AvarianKnight** [comment]
Sorry, I haven't been active in maintenance, can you show me how you reproduce this as I am not able to replicate.
