### ISSUE TITLE
smart_cleanup does not work.

### ISSUE THREAD

**Issue by Aws0mee** [NanoAi/gm_apg#27]
I saw you guys fixed the last issue I posted. This issue has been around way longer, around 6 months or so. The smart_cleanup function when run makes it so no props can be spawned or picked up with a physgun.

**Comment by AvarianKnight** [comment]
Can you post any error logs you might have.

**Comment by Aws0mee** [comment]
no

**Comment by AvarianKnight** [comment]
I'm going to close this as it doesn't seem anyone else is having the issue.
