### ISSUE TITLE
Problem with ARCbank entity

### ISSUE THREAD

**Issue by AlexNova1555** [NanoAi/gm_apg#29]
Hey there :D 
so after i have install APG on my server i got problems with arcbank
when i insert the card into the item the card just fly away from the ATM instead of going inside the item
same goes for the money
when i insert or depost the money from the ATM it just fly up 

i looked up at APG setting and only when i disabled Ghosting setting on APG its gets back to normal the ARCBANK

here how its look like
https://gph.is/g/4LNkWjR

hope you can help me with that

**Comment by AvarianKnight** [comment]
Can you provide me with your settings (should be in data/apg) and post it into http://hasteb.in/

**Comment by AlexNova1555** [comment]
yea here
https://hasteb.in/jejokifu.json

**Comment by AlexNova1555** [comment]
Any help?

**Comment by TomDotBat** [comment]
I'm getting the exact same behaviour, didn't know APG caused this. I'll let you know if I find a solution.

**Comment by AvarianKnight** [comment]
Should be fixed with #32
