### ISSUE TITLE
Alot of errors after server startup

### ISSUE THREAD

**Issue by AlexNova1555** [NanoAi/gm_apg#3]
Hey there ^_^
So im getting alot errors after the server has started up and i don't know why is this happening
can you please check it out?
here are the errors
https://pastebin.com/eR0xwdFF

**Comment by NanoAi** [comment]
You have some addon on your server that's creating a NULL entity.

**Comment by AlexNova1555** [comment]
yea i found out it was the some props with the map but i dont know what prop is it...
is there any way to make my server to ignore the error?

**Comment by NanoAi** [comment]
You can try removing the entities by default so the error doesn't happen.
Make sure you have a prop protection addon like FPP and make sure those
entities are flagged as world entities as well.

**Comment by AlexNova1555** [comment]
yap i found the props that cause the problems thanks for your support!
