### ISSUE TITLE
Add the ability to whitelist certain entities from anti prop kill ( request )

### ISSUE THREAD

**Issue by Synkstar** [NanoAi/gm_apg#30]
Some addons like Alydus base systems(https://steamcommunity.com/sharedfiles/filedetails/?id=1579980201) get broken because of the anti prop kill. It would be nice if you could somehow whitelist certain entities from it to prevent breaking

**Comment by AvarianKnight** [comment]
Hey, @Smartjer123 currently APG is in maintenance mode (if you want to call it that) and will not be getting any features added. 

On a side note, if the addon doesn't use prop_physics then you have to specifically blacklist certain addons. And another detail I would like to add is that you are able to "whitelist" entities to be frozen after they are picked up.
