### ISSUE TITLE
Colors not Saving

### ISSUE THREAD

**Issue by FrezZyyyx** [NanoAi/gm_apg#31]
Theres an issue where if you use a material on a prop then use the color tool to change the color, then dupe it and save it and when you paste it, the colors dont save and its really annoying. I soon found out that APG is the cause here and its to do with the ghosting module i believe, i disabled it and the colors saved but that means people can prop surf etc so this needs to be fixed asap.

**Comment by AvarianKnight** [comment]
Should be fixed in the latest commit.
