### ISSUE TITLE
Physics engine crash?

### ISSUE THREAD

**Issue by Awsomethefirst** [NanoAi/gm_apg#4]
It appears the function smart_cleanup may be breaking stuff. Randomly on my server the anti crash will just keep getting triggered like 5 times in 10 seconds even when the server isnt lagging. For some reason when this happens doors get stuck in place and nobody can move props with any method(physgun, gravitygun, shooting at them). This is really odd and im not sure why this is happening but it seems kind of odd.

**Comment by NanoAi** [comment]
Try adjusting your lag tolerance in your setting, if that doesn't work switch to a different cleanup method.

**Comment by Awsomethefirst** [comment]
I have done this for now but it seems like the most useful method. I hope this fixes everything.

**Comment by NanoAi** [comment]
Basically if you get lag triggers when the server isn't lagging the algorithm just thinks that the server is lagging and needs to have its numbers adjusted. Some day I may make something better but recently I've not been playing much gmod so I'm not going to promise anything. (Plus it would require some major edits.)
