### ISSUE TITLE
[Bug] Players unable to physgun props

### ISSUE THREAD

**Issue by sarahsturgeon** [NanoAi/gm_apg#43]
Getting a bug that is critically affecting servers, preventing people from picking up most world objects. Also getting reports that it could affect duping and e2s/starfalls but have no evidence of those.

```
[ERROR] addons/gm_apg/lua/apg/sv_apg.lua:29: attempt to index global 'APG_HeldBy' (a nil value)
[09:50:33] 1. canPhysGun - addons/gm_apg/lua/apg/sv_apg.lua:29
[09:50:33] 2. fn - addons/gm_apg/lua/apg/modules/canphysgun.lua:20
[09:50:33] 3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
```

Looks like this is the line that broke things, committed 12 hours ago:
https://github.com/NanoAi/gm_apg/commit/cfc103e0225dbae2a16e664503b740ac2043bdd4?w=1#diff-d32fe0277cafbd72eee7c9f813c6f629R29

**Comment by AvarianKnight** [comment]
I'll revert the commit for right now and fix it when I get home.

**Comment by AvarianKnight** [comment]
Nevermind, Nano fixed it.

**Comment by NanoAi** [comment]
~~I think I fixed it but I've not tested it, although I don't see why it wouldn't work now. I'll leave this open, to confirm that it is in fact fixed.~~
This has now been tested, and is confirmed fixed!
