### ISSUE TITLE
Big props not unghosting

### ISSUE THREAD

**Issue by FrezZyyyx** [NanoAi/gm_apg#45]
when i spawn in more thicker props and try to unghost them with physgun it doesnt work?? i can upload a video if u want.

**Comment by AvarianKnight** [comment]
IIRC that's FPP not APG

**Comment by FrezZyyyx** [comment]
i havent changed anything though with FPP?

**Comment by FrezZyyyx** [comment]
wait actually i did update to newest dark rp version so
