### ISSUE TITLE
Prop Pushing Cars Works

### ISSUE THREAD

**Issue by briang112** [NanoAi/gm_apg#5]
Hi, ever since the latest version people have been able to freeze props in cars, thus pushing them across the map.

**Comment by boltseller** [comment]
Was about to post the same issue!

**Comment by NanoAi** [comment]
Not sure what "latest" version means, you can rollback to whatever version you'd like using github however. I've tried my best to make vehicle detection perfect, but I'm not perfect so neither is my code.

Help and pull requests are much appreciated!
