### ISSUE TITLE
Receiving NULL Entity Error

### ISSUE THREAD

**Issue by ghost** [NanoAi/gm_apg#6]
```
[ERROR] addons/addon_apg/lua/apg/modules/ghosting.lua:259: Tried to use a NULL entity!
1. DropEntityIfHeld - [C]:-1
2. unknown - addons/addon_apg/lua/apg/modules/ghosting.lua:259
Timer Failed! [Simple][@addons/addon_apg/lua/apg/modules/ghosting.lua (line 256)]
```

This is an error I receive very occasionally; I don't entirely know what causes it or if it's something to be concerned about. I haven't been able to identify any common circumstances under which this issue occurs.

**Comment by zakarybk** [comment]
I got a very similar one.
[ERROR] addons/gm_apg/lua/apg/modules/ghosting.lua:265: Tried to use a NULL entity!
  1. DropEntityIfHeld - [C]:-1
   2. unknown - addons/gm_apg/lua/apg/modules/ghosting.lua:265

**Comment by NanoAi** [comment]
These errors shouldn't be happening anymore, if they are still here. Reopen the issue to let people know.
